import pandas as pd
import os

# --- PATHS ---
GEO_CSV = "data/processed/stations_geocoded.csv"

# --- THE CHEAT SHEET (7 DECIMAL PLACES) ---
MANUAL_OVERRIDES = {
    "Raikhad": (23.0238000, 72.5797000),
    "SAC ISRO Bopal": (23.0294000, 72.4646000),
    "SAC ISRO Satellite": (23.0250000, 72.5200000),
    "SVPI Airport Hansol": (23.0674000, 72.6320000),
    "Sardar Vallabhbhai Patel Stadium": (23.0916000, 72.5976000),
    "BWSSB Kadabesanahalli": (12.9354000, 77.6946000),
    "Sanegurava Halli": (12.9856000, 77.5342000),
    "Alandur Bus Depot": (13.0031000, 80.2014000),
    "Manali Village": (13.1770000, 80.2630000),
    "Velachery Res. Area": (12.9750000, 80.2200000),
    "IHBAS": (28.6823000, 77.3183000), 
    "IHBAS, Dilshad Garden": (28.6823000, 77.3183000),
    "DTU": (28.7501000, 77.1177000),
    "CRRI Mathura Road": (28.5535000, 77.2790000),
    "NSIT Dwarka": (28.6091000, 77.0350000),
    "Sonia Vihar": (28.7329000, 77.2472000),
    "Bollaram Industrial Area": (17.5501000, 78.3314000),
    "ICRISAT Patancheru": (17.5111000, 78.2752000),
    "IDA Pashamylaram": (17.5285000, 78.1901000),
    "IITH Kandi": (17.5947000, 78.1230000),
    "Kompally Municipal Office": (17.5457000, 78.4831000),
    "Nacharam_TSIIC IALA": (17.4243000, 78.5714000),
    "Chhatrapati Shivaji Intl. Airport (T2)": (19.0974000, 72.8743000),
    "Siddharth Nagar-Worli": (19.0146000, 72.8173000),
    "Mhada Colony": (18.6015000, 73.8214000),
    "Panchawati_Pashan": (18.5363000, 73.8054000),
    "Vasai West": (19.3840000, 72.8258000),
}

def fix_csv():
    print(" Initializing CSV Patch Script...")
    
    if not os.path.exists(GEO_CSV):
        print(f" ERROR: Cannot find {GEO_CSV}.")
        return

    # Load the CSV generated by the web scraper
    geo_df = pd.read_csv(GEO_CSV)
    
    missing_mask = geo_df['latitude'].isna()
    missing_count = missing_mask.sum()
    print(f"Found {missing_count} stations missing coordinates.")
    
    patched_count = 0
    for idx, row in geo_df[missing_mask].iterrows():
        station_name = str(row['station']).strip()
        
        if station_name in MANUAL_OVERRIDES:
            lat, lon = MANUAL_OVERRIDES[station_name]
            geo_df.at[idx, 'latitude'] = lat
            geo_df.at[idx, 'longitude'] = lon
            print(f"   PATCHED: {station_name} -> {lat:.7f}, {lon:.7f}")
            patched_count += 1
        else:
            print(f"   UNKNOWN: '{station_name}' is not in the cheat sheet!")

    # Save the patched CSV back with exactly 7 decimal places for consistency
    geo_df.to_csv(GEO_CSV, index=False, float_format='%.7f')
    print(f"\n Saved {patched_count} patches to {GEO_CSV}.")

    # Verify if we fixed everything
    remaining_missing = geo_df['latitude'].isna().sum()
    if remaining_missing == 0:
        print("\n SUCCESS: stations_geocoded.csv is 100% complete and perfectly formatted.")
    else:
        print(f"\n WARNING: {remaining_missing} stations are still missing.")

if __name__ == "__main__":
    fix_csv()