import pandas as pd
import sys
import os
import numpy as np

FILE_PATH = "data/processed/features/advection_features.parquet"

# The exact schema columns generated by the multi-pollutant engine
POLLUTANTS = ['PM2.5_µg/m³', 'PM10_µg/m³', 'NO2_µg/m³', 'SO2_µg/m³', 'CO_mg/m³']
EXPECTED_COLS = [f'adv_in_{pol}' for pol in POLLUTANTS]

def verify_advection_layer():
    print("INITIALIZING ADVECTION PHYSICS VERIFICATION SUITE...\n")

    if not os.path.exists(FILE_PATH):
        print(f"[ERROR] File not found: {FILE_PATH}")
        sys.exit(1)

    try:
        print(f"[INFO] Loading {FILE_PATH}. This may take a moment...")
        df = pd.read_parquet(FILE_PATH)
    except Exception as e:
        print(f"[ERROR] Failed to load Parquet file: {e}")
        sys.exit(1)

    # TEST 1: Dataset Shape & Integrity
    print("\n=== TEST 1: DATASET INTEGRITY ===")
    print(f"Total Rows: {df.shape[0]:,}")
    # The row count MUST match the ~13.4 million rows from the previous verification exactly.
    if df.shape[0] < 13000000:
        print("[WARNING] Row count seems significantly lower than expected.")
    else:
        print("[SUCCESS] Massive spatiotemporal grid scale maintained.")

    # TEST 2: Schema Validation
    print("\n=== TEST 2: ADVECTION SCHEMA VALIDATION ===")
    missing_cols = [col for col in EXPECTED_COLS if col not in df.columns]
    if missing_cols:
        print(f"[ERROR] Missing required advection columns: {missing_cols}")
        sys.exit(1)
    else:
        print("[SUCCESS] All multi-pollutant advection features are present.")

    # TEST 3: Null Value Check
    print("\n=== TEST 3: COMPLETENESS (NULL CHECK) ===")
    null_counts = df[EXPECTED_COLS].isna().sum()
    total_nulls = null_counts.sum()
    if total_nulls == 0:
        print("[SUCCESS] 0 Null values found. Fillna(0) successfully applied.")
    else:
        print("[ERROR] Found Null values in advection columns:")
        print(null_counts[null_counts > 0].to_string())

    # TEST 4: Physical Constraints (ReLU Check)
    print("\n=== TEST 4: PHYSICAL CONSTRAINTS (NO BACKWARD FLOW) ===")
    negative_flow_violations = 0
    for col in EXPECTED_COLS:
        min_val = df[col].min()
        if min_val < 0:
            negative_flow_violations += 1
            print(f"[ERROR] Negative advection found in {col} (Min: {min_val}). Physical logic breached.")
            
    if negative_flow_violations == 0:
        print("[SUCCESS] All advection values >= 0. Upwind ReLU filter functioning perfectly.")

    # TEST 5: Mathematical Activation (Signal Check)
    print("\n=== TEST 5: ADVECTION SIGNAL VERIFICATION ===")
    print("Checking if the network generated non-zero influence signals...")
    for col in EXPECTED_COLS:
        max_val = df[col].max()
        mean_val = df[col][df[col] > 0].mean() # Mean of active advection events
        
        if max_val > 0:
            print(f" - {col}: Max Flux = {max_val:.2f}, Active Mean = {mean_val:.2f}")
        else:
            print(f" [WARNING] {col} is entirely zeros. Check dispersion logic.")

    print("\n[INFO] VERIFICATION COMPLETE.")

if __name__ == "__main__":
    verify_advection_layer()